# MegaLinter Configuration File
# Documentation: https://megalinter.io/latest/configuration/

# Apply linters only on specific file types
APPLY_FIXES: none  # Don't auto-fix in CI (use 'all' for local development)

# Enable only Terraform-related linters
ENABLE:
  - TERRAFORM

# Terraform linters configuration
TERRAFORM_TERRAFORM_FMT_ARGUMENTS:
  - -check
  - -recursive

TERRAFORM_TFLINT_ARGUMENTS:
  - --recursive
  - --minimum-failure-severity=error

# Filter files to analyze
FILTER_REGEX_EXCLUDE: |
  (\.terraform/|\.terraform\.lock\.hcl|terraform\.tfstate|terraform\.tfstate\.backup)

# File extensions to process
TERRAFORM_FILE_EXTENSIONS:
  - .tf
  - .tfvars

# Limit Terraform linters to directories that actually contain Terraform code
# to avoid scanning docs, templates and other non-TF folders in this repo.
# Re-enable Terrascan and only scan the listed directories.
TERRAFORM_SCAN_DIRECTORIES:
  - .
  - modules/compute
  - modules/k3s
  - modules/kafka
  - modules/network

# Re-enable Terrascan (was previously disabled to avoid errors on empty dirs).
# If you prefer to keep it disabled, remove the following block.
ENABLE_LINTERS_OVERRIDES: |
  - TERRAFORM_TERRASCAN

# Disable specific linters if needed (uncomment to disable)
# DISABLE_LINTERS:
#   - TERRAFORM_CHECKOV  # Disable Checkov if too strict
#   - TERRAFORM_TERRASCAN  # Disable Terrascan if not needed

# Report configuration
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false  # Disable file.io upload for security

# GitHub integration
GITHUB_COMMENT_REPORTER: true  # Post results as PR comments
UPDATED_SOURCES_REPORTER: false  # Don't create fix PRs automatically
