apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: trading-cluster
  namespace: kafka
spec:
  kafka:
    resources:
      requests:
        memory: 3Gi
        cpu: "1"
      limits:
        memory: 6Gi
        cpu: "3"
    jvmOptions:
      -Xms: 2560m
      -Xmx: 2560m
