apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: trading-cluster
  namespace: kafka
spec:
  kafka:
    version: 4.0.0
    replicas: 3
    
    # Node selector to place Kafka pods on kafka-labeled nodes
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/kafka
                      operator: In
                      values:
                        - "true"
    
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 32100
    
    config:
      # KRaft mode configuration
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      
      # Performance tuning
      num.network.threads: 3
      num.io.threads: 8
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      
      # Topic configuration
      auto.create.topics.enable: true
      log.retention.hours: 72
      log.segment.bytes: 1073741824
      log.retention.check.interval.ms: 300000
      
      # Compression
      compression.type: lz4
      
    storage:
      type: ephemeral
    
    resources:
      requests:
        memory: 3Gi
        cpu: "1"
      limits:
        memory: 6Gi
        cpu: "3"
    
    jvmOptions:
      -Xms: 2560m
      -Xmx: 2560m
    
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  
  # Entity Operator for topic and user management
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: "100m"
        limits:
          memory: 256Mi
          cpu: "500m"
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: "100m"
        limits:
          memory: 256Mi
          cpu: "500m"
