apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-example
  namespace: ingestion
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ingestion
        env:
        - name: ENVIRONMENT
          value: "prod"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-example
  namespace: strategies
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: strategy
        env:
        - name: ENVIRONMENT
          value: "prod"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "500m"
