apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: trading-system-project
  
  source:
    repoURL: 'https://github.com/trading-cz/infra.git'
    targetRevision: main
    path: kubernetes/overlays/dev/kafka  # or prod/kafka for production
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
  
  # Health assessment
  health:
    - kind: Kafka
      check: |
        hs = {}
        if obj.status ~= nil and obj.status.conditions ~= nil then
          for i, condition in ipairs(obj.status.conditions) do
            if condition.type == "Ready" and condition.status == "True" then
              hs.status = "Healthy"
              hs.message = "Kafka cluster is ready"
              return hs
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for Kafka cluster"
        return hs
