apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trading-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: trading-system-project
  
  source:
    repoURL: 'https://github.com/trading-cz/infra.git'
    targetRevision: main
    path: kubernetes/overlays/dev/apps  # or prod/apps for production
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
  
  # Sync wave: Deploy after Kafka is ready
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "10"
